podSecurityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
  seccompProfile: &id001
    type: RuntimeDefault
securityContext:
  enabled: true
  runAsUser: 10001
  runAsGroup: 10001
resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 256Mi
webhook:
  podSecurityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 10001
    runAsGroup: 10001
    fsGroup: 10001
    seccompProfile: *id001
  securityContext:
    enabled: true
    runAsUser: 10001
    runAsGroup: 10001
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 256Mi
certController:
  podSecurityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 10001
    runAsGroup: 10001
    fsGroup: 10001
    seccompProfile: *id001
  securityContext:
    enabled: true
    runAsUser: 10001
    runAsGroup: 10001
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 256Mi
