controller:
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 101
    runAsGroup: 82
    seccompProfile:
      type: RuntimeDefault
  resources:
    requests:
      cpu: 100m
      memory: 90Mi
    limits:
      cpu: '1'
      memory: 512Mi
  admissionWebhooks:
    createSecretJob:
      resources:
        requests:
          cpu: 10m
          memory: 16Mi
        limits:
          cpu: 100m
          memory: 64Mi
    patchWebhookJob:
      resources:
        requests:
          cpu: 10m
          memory: 16Mi
        limits:
          cpu: 100m
          memory: 64Mi
